---
- name: RedHat
  include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Windows
  include: windows.yml
  when: ansible_os_family == 'Windows'

- name: add custom properties to solarwinds node
  sw_manage:
    hostname: '{{ agent_secrets.sw_hostname }}'
    username: '{{ ent_domain.username }}'
    password: '{{ ent_domain.password }}'
    state: "update"
    caption: "{{ hostvars[inventory_hostname]['ansible_facts']['hostname'] }}"
    env: '{{ env }}'
    fisma: '{{ fisma }}'
    project_lead: '{{ project_lead }}'
    sme: '{{ sme }}'
  delegate_to: localhost
  run_once: true
  retries: 5
  delay: 15
  ignore_errors: true
