---
- name: copying swiagent.tar.gz to /tmp for install
  get_url:
    url: '{{ redhat_solarwinds_agent_path }}'
    dest: /tmp/swiagent.tar.gz

- name: extract swiagent.tar.gz to /tmp for install
  unarchive:
    src: /tmp/swiagent.tar.gz
    dest: /tmp/swiagent

- name: change shell permissions for swiagent
  file:
    path: /tmp/swiagent
    state: directory
    recurse: yes
    mode: a+x

- name: execute install.sh for swiagent
  shell: /tmp/install.sh >> /tmp/solarwinds_install.txt
