---
- name: checking for agent install
  win_stat:
    path: '{{ windows_solarwinds_agent_path }}'
  register: path

- debug:
    msg: "solarwinds agent not found"
  when: path.stat.islnk is not defined

- debug:
    msg: "solarwinds agent found skipping install"
  when: path.stat.islnk is defined

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory
  when: path.stat.islnk is not defined

- name: create {{ windows_solarwinds_agent_path }} directory
  win_file:
    path: '{{ windows_solarwinds_agent_path }}'
    recurse: yes
    state: directory
  when: path.stat.islnk is not defined

- name: copy solarwinds-agent.mst to {{ windows_solarwinds_agent_path }} directory
  win_get_url:
    url: '{{ solarwinds_agent_config_url }}'
    dest: '{{ windows_solarwinds_agent_path }}\\SolarWinds-Agent.mst'
  when: path.stat.islnk is not defined

- name: install solarwinds agent (windows)
  win_package:
    path: '{{ windows_solarwinds_agent_url }}'
    log_path: '{{ windows_agent_log }}\\solarwinds_log.txt'
    product_id: '{{ windows_solarwinds_product_id }}'
    validate_certs: no
    state: present
    arguments: /qn
  when: path.stat.islnk is not defined

- name: verify solarwinds started
  win_service:
    name: solarwindsagent64
    state: started
